// Code generated by Kitex v0.9.1. DO NOT EDIT.

package productcatalogservice

import (
	"context"
	product "douyin_mall/rpc/kitex_gen/product"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListProducts": kitex.NewMethodInfo(
		listProductsHandler,
		newListProductsArgs,
		newListProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newGetProductArgs,
		newGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchProducts": kitex.NewMethodInfo(
		searchProductsHandler,
		newSearchProductsArgs,
		newSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"InsertProduct": kitex.NewMethodInfo(
		insertProductHandler,
		newInsertProductArgs,
		newInsertProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SelectProduct": kitex.NewMethodInfo(
		selectProductHandler,
		newSelectProductArgs,
		newSelectProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteProduct": kitex.NewMethodInfo(
		deleteProductHandler,
		newDeleteProductArgs,
		newDeleteProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateProduct": kitex.NewMethodInfo(
		updateProductHandler,
		newUpdateProductArgs,
		newUpdateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SelectCategory": kitex.NewMethodInfo(
		selectCategoryHandler,
		newSelectCategoryArgs,
		newSelectCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"InsertCategory": kitex.NewMethodInfo(
		insertCategoryHandler,
		newInsertCategoryArgs,
		newInsertCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteCategory": kitex.NewMethodInfo(
		deleteCategoryHandler,
		newDeleteCategoryArgs,
		newDeleteCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateCategory": kitex.NewMethodInfo(
		updateCategoryHandler,
		newUpdateCategoryArgs,
		newUpdateCategoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SelectBrand": kitex.NewMethodInfo(
		selectBrandHandler,
		newSelectBrandArgs,
		newSelectBrandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"InsertBrand": kitex.NewMethodInfo(
		insertBrandHandler,
		newInsertBrandArgs,
		newInsertBrandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteBrand": kitex.NewMethodInfo(
		deleteBrandHandler,
		newDeleteBrandArgs,
		newDeleteBrandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateBrand": kitex.NewMethodInfo(
		updateBrandHandler,
		newUpdateBrandArgs,
		newUpdateBrandResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	productCatalogServiceServiceInfo                = NewServiceInfo()
	productCatalogServiceServiceInfoForClient       = NewServiceInfoForClient()
	productCatalogServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productCatalogServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductCatalogService"
	handlerType := (*product.ProductCatalogService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func listProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.ListProductsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).ListProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListProductsArgs:
		success, err := handler.(product.ProductCatalogService).ListProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListProductsArgs() interface{} {
	return &ListProductsArgs{}
}

func newListProductsResult() interface{} {
	return &ListProductsResult{}
}

type ListProductsArgs struct {
	Req *product.ListProductsReq
}

func (p *ListProductsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.ListProductsReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListProductsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListProductsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListProductsArgs) Unmarshal(in []byte) error {
	msg := new(product.ListProductsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListProductsArgs_Req_DEFAULT *product.ListProductsReq

func (p *ListProductsArgs) GetReq() *product.ListProductsReq {
	if !p.IsSetReq() {
		return ListProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListProductsResult struct {
	Success *product.ListProductsResp
}

var ListProductsResult_Success_DEFAULT *product.ListProductsResp

func (p *ListProductsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.ListProductsResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListProductsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListProductsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListProductsResult) Unmarshal(in []byte) error {
	msg := new(product.ListProductsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListProductsResult) GetSuccess() *product.ListProductsResp {
	if !p.IsSetSuccess() {
		return ListProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.ListProductsResp)
}

func (p *ListProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListProductsResult) GetResult() interface{} {
	return p.Success
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.GetProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).GetProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetProductArgs:
		success, err := handler.(product.ProductCatalogService).GetProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetProductArgs() interface{} {
	return &GetProductArgs{}
}

func newGetProductResult() interface{} {
	return &GetProductResult{}
}

type GetProductArgs struct {
	Req *product.GetProductReq
}

func (p *GetProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.GetProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetProductArgs) Unmarshal(in []byte) error {
	msg := new(product.GetProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetProductArgs_Req_DEFAULT *product.GetProductReq

func (p *GetProductArgs) GetReq() *product.GetProductReq {
	if !p.IsSetReq() {
		return GetProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetProductResult struct {
	Success *product.GetProductResp
}

var GetProductResult_Success_DEFAULT *product.GetProductResp

func (p *GetProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.GetProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetProductResult) Unmarshal(in []byte) error {
	msg := new(product.GetProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetProductResult) GetSuccess() *product.GetProductResp {
	if !p.IsSetSuccess() {
		return GetProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.GetProductResp)
}

func (p *GetProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetProductResult) GetResult() interface{} {
	return p.Success
}

func searchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.SearchProductsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).SearchProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchProductsArgs:
		success, err := handler.(product.ProductCatalogService).SearchProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchProductsArgs() interface{} {
	return &SearchProductsArgs{}
}

func newSearchProductsResult() interface{} {
	return &SearchProductsResult{}
}

type SearchProductsArgs struct {
	Req *product.SearchProductsReq
}

func (p *SearchProductsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.SearchProductsReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SearchProductsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SearchProductsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SearchProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchProductsArgs) Unmarshal(in []byte) error {
	msg := new(product.SearchProductsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchProductsArgs_Req_DEFAULT *product.SearchProductsReq

func (p *SearchProductsArgs) GetReq() *product.SearchProductsReq {
	if !p.IsSetReq() {
		return SearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchProductsResult struct {
	Success *product.SearchProductsResp
}

var SearchProductsResult_Success_DEFAULT *product.SearchProductsResp

func (p *SearchProductsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.SearchProductsResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SearchProductsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SearchProductsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SearchProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchProductsResult) Unmarshal(in []byte) error {
	msg := new(product.SearchProductsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchProductsResult) GetSuccess() *product.SearchProductsResp {
	if !p.IsSetSuccess() {
		return SearchProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.SearchProductsResp)
}

func (p *SearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchProductsResult) GetResult() interface{} {
	return p.Success
}

func insertProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.InsertProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).InsertProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *InsertProductArgs:
		success, err := handler.(product.ProductCatalogService).InsertProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*InsertProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newInsertProductArgs() interface{} {
	return &InsertProductArgs{}
}

func newInsertProductResult() interface{} {
	return &InsertProductResult{}
}

type InsertProductArgs struct {
	Req *product.InsertProductReq
}

func (p *InsertProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.InsertProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *InsertProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *InsertProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *InsertProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *InsertProductArgs) Unmarshal(in []byte) error {
	msg := new(product.InsertProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var InsertProductArgs_Req_DEFAULT *product.InsertProductReq

func (p *InsertProductArgs) GetReq() *product.InsertProductReq {
	if !p.IsSetReq() {
		return InsertProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *InsertProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InsertProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type InsertProductResult struct {
	Success *product.InsertProductResp
}

var InsertProductResult_Success_DEFAULT *product.InsertProductResp

func (p *InsertProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.InsertProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *InsertProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *InsertProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *InsertProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *InsertProductResult) Unmarshal(in []byte) error {
	msg := new(product.InsertProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *InsertProductResult) GetSuccess() *product.InsertProductResp {
	if !p.IsSetSuccess() {
		return InsertProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *InsertProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.InsertProductResp)
}

func (p *InsertProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InsertProductResult) GetResult() interface{} {
	return p.Success
}

func selectProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.SelectProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).SelectProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SelectProductArgs:
		success, err := handler.(product.ProductCatalogService).SelectProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SelectProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSelectProductArgs() interface{} {
	return &SelectProductArgs{}
}

func newSelectProductResult() interface{} {
	return &SelectProductResult{}
}

type SelectProductArgs struct {
	Req *product.SelectProductReq
}

func (p *SelectProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.SelectProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SelectProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SelectProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SelectProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SelectProductArgs) Unmarshal(in []byte) error {
	msg := new(product.SelectProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SelectProductArgs_Req_DEFAULT *product.SelectProductReq

func (p *SelectProductArgs) GetReq() *product.SelectProductReq {
	if !p.IsSetReq() {
		return SelectProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SelectProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SelectProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SelectProductResult struct {
	Success *product.SelectProductResp
}

var SelectProductResult_Success_DEFAULT *product.SelectProductResp

func (p *SelectProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.SelectProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SelectProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SelectProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SelectProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SelectProductResult) Unmarshal(in []byte) error {
	msg := new(product.SelectProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SelectProductResult) GetSuccess() *product.SelectProductResp {
	if !p.IsSetSuccess() {
		return SelectProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SelectProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.SelectProductResp)
}

func (p *SelectProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SelectProductResult) GetResult() interface{} {
	return p.Success
}

func deleteProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.DeleteProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).DeleteProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteProductArgs:
		success, err := handler.(product.ProductCatalogService).DeleteProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteProductArgs() interface{} {
	return &DeleteProductArgs{}
}

func newDeleteProductResult() interface{} {
	return &DeleteProductResult{}
}

type DeleteProductArgs struct {
	Req *product.DeleteProductReq
}

func (p *DeleteProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.DeleteProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteProductArgs) Unmarshal(in []byte) error {
	msg := new(product.DeleteProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteProductArgs_Req_DEFAULT *product.DeleteProductReq

func (p *DeleteProductArgs) GetReq() *product.DeleteProductReq {
	if !p.IsSetReq() {
		return DeleteProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteProductResult struct {
	Success *product.DeleteProductResp
}

var DeleteProductResult_Success_DEFAULT *product.DeleteProductResp

func (p *DeleteProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.DeleteProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteProductResult) Unmarshal(in []byte) error {
	msg := new(product.DeleteProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteProductResult) GetSuccess() *product.DeleteProductResp {
	if !p.IsSetSuccess() {
		return DeleteProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.DeleteProductResp)
}

func (p *DeleteProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteProductResult) GetResult() interface{} {
	return p.Success
}

func updateProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.UpdateProductReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).UpdateProduct(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateProductArgs:
		success, err := handler.(product.ProductCatalogService).UpdateProduct(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateProductResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateProductArgs() interface{} {
	return &UpdateProductArgs{}
}

func newUpdateProductResult() interface{} {
	return &UpdateProductResult{}
}

type UpdateProductArgs struct {
	Req *product.UpdateProductReq
}

func (p *UpdateProductArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.UpdateProductReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateProductArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateProductArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateProductArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateProductArgs) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateProductArgs_Req_DEFAULT *product.UpdateProductReq

func (p *UpdateProductArgs) GetReq() *product.UpdateProductReq {
	if !p.IsSetReq() {
		return UpdateProductArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateProductArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateProductResult struct {
	Success *product.UpdateProductResp
}

var UpdateProductResult_Success_DEFAULT *product.UpdateProductResp

func (p *UpdateProductResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.UpdateProductResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateProductResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateProductResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateProductResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateProductResult) Unmarshal(in []byte) error {
	msg := new(product.UpdateProductResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateProductResult) GetSuccess() *product.UpdateProductResp {
	if !p.IsSetSuccess() {
		return UpdateProductResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.UpdateProductResp)
}

func (p *UpdateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateProductResult) GetResult() interface{} {
	return p.Success
}

func selectCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.CategorySelectReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).SelectCategory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SelectCategoryArgs:
		success, err := handler.(product.ProductCatalogService).SelectCategory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SelectCategoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSelectCategoryArgs() interface{} {
	return &SelectCategoryArgs{}
}

func newSelectCategoryResult() interface{} {
	return &SelectCategoryResult{}
}

type SelectCategoryArgs struct {
	Req *product.CategorySelectReq
}

func (p *SelectCategoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.CategorySelectReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SelectCategoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SelectCategoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SelectCategoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SelectCategoryArgs) Unmarshal(in []byte) error {
	msg := new(product.CategorySelectReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SelectCategoryArgs_Req_DEFAULT *product.CategorySelectReq

func (p *SelectCategoryArgs) GetReq() *product.CategorySelectReq {
	if !p.IsSetReq() {
		return SelectCategoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SelectCategoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SelectCategoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SelectCategoryResult struct {
	Success *product.CategorySelectResp
}

var SelectCategoryResult_Success_DEFAULT *product.CategorySelectResp

func (p *SelectCategoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.CategorySelectResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SelectCategoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SelectCategoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SelectCategoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SelectCategoryResult) Unmarshal(in []byte) error {
	msg := new(product.CategorySelectResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SelectCategoryResult) GetSuccess() *product.CategorySelectResp {
	if !p.IsSetSuccess() {
		return SelectCategoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SelectCategoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.CategorySelectResp)
}

func (p *SelectCategoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SelectCategoryResult) GetResult() interface{} {
	return p.Success
}

func insertCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.CategoryInsertReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).InsertCategory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *InsertCategoryArgs:
		success, err := handler.(product.ProductCatalogService).InsertCategory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*InsertCategoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newInsertCategoryArgs() interface{} {
	return &InsertCategoryArgs{}
}

func newInsertCategoryResult() interface{} {
	return &InsertCategoryResult{}
}

type InsertCategoryArgs struct {
	Req *product.CategoryInsertReq
}

func (p *InsertCategoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.CategoryInsertReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *InsertCategoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *InsertCategoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *InsertCategoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *InsertCategoryArgs) Unmarshal(in []byte) error {
	msg := new(product.CategoryInsertReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var InsertCategoryArgs_Req_DEFAULT *product.CategoryInsertReq

func (p *InsertCategoryArgs) GetReq() *product.CategoryInsertReq {
	if !p.IsSetReq() {
		return InsertCategoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *InsertCategoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InsertCategoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type InsertCategoryResult struct {
	Success *product.CategoryInsertResp
}

var InsertCategoryResult_Success_DEFAULT *product.CategoryInsertResp

func (p *InsertCategoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.CategoryInsertResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *InsertCategoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *InsertCategoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *InsertCategoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *InsertCategoryResult) Unmarshal(in []byte) error {
	msg := new(product.CategoryInsertResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *InsertCategoryResult) GetSuccess() *product.CategoryInsertResp {
	if !p.IsSetSuccess() {
		return InsertCategoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *InsertCategoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.CategoryInsertResp)
}

func (p *InsertCategoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InsertCategoryResult) GetResult() interface{} {
	return p.Success
}

func deleteCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.CategoryDeleteReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).DeleteCategory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteCategoryArgs:
		success, err := handler.(product.ProductCatalogService).DeleteCategory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteCategoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteCategoryArgs() interface{} {
	return &DeleteCategoryArgs{}
}

func newDeleteCategoryResult() interface{} {
	return &DeleteCategoryResult{}
}

type DeleteCategoryArgs struct {
	Req *product.CategoryDeleteReq
}

func (p *DeleteCategoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.CategoryDeleteReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteCategoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteCategoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteCategoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteCategoryArgs) Unmarshal(in []byte) error {
	msg := new(product.CategoryDeleteReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteCategoryArgs_Req_DEFAULT *product.CategoryDeleteReq

func (p *DeleteCategoryArgs) GetReq() *product.CategoryDeleteReq {
	if !p.IsSetReq() {
		return DeleteCategoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteCategoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteCategoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteCategoryResult struct {
	Success *product.CategoryDeleteResp
}

var DeleteCategoryResult_Success_DEFAULT *product.CategoryDeleteResp

func (p *DeleteCategoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.CategoryDeleteResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteCategoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteCategoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteCategoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteCategoryResult) Unmarshal(in []byte) error {
	msg := new(product.CategoryDeleteResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteCategoryResult) GetSuccess() *product.CategoryDeleteResp {
	if !p.IsSetSuccess() {
		return DeleteCategoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteCategoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.CategoryDeleteResp)
}

func (p *DeleteCategoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteCategoryResult) GetResult() interface{} {
	return p.Success
}

func updateCategoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.CategoryUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).UpdateCategory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateCategoryArgs:
		success, err := handler.(product.ProductCatalogService).UpdateCategory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateCategoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateCategoryArgs() interface{} {
	return &UpdateCategoryArgs{}
}

func newUpdateCategoryResult() interface{} {
	return &UpdateCategoryResult{}
}

type UpdateCategoryArgs struct {
	Req *product.CategoryUpdateReq
}

func (p *UpdateCategoryArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.CategoryUpdateReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateCategoryArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateCategoryArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateCategoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateCategoryArgs) Unmarshal(in []byte) error {
	msg := new(product.CategoryUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateCategoryArgs_Req_DEFAULT *product.CategoryUpdateReq

func (p *UpdateCategoryArgs) GetReq() *product.CategoryUpdateReq {
	if !p.IsSetReq() {
		return UpdateCategoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateCategoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateCategoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateCategoryResult struct {
	Success *product.CategoryUpdateResp
}

var UpdateCategoryResult_Success_DEFAULT *product.CategoryUpdateResp

func (p *UpdateCategoryResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.CategoryUpdateResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateCategoryResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateCategoryResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateCategoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateCategoryResult) Unmarshal(in []byte) error {
	msg := new(product.CategoryUpdateResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateCategoryResult) GetSuccess() *product.CategoryUpdateResp {
	if !p.IsSetSuccess() {
		return UpdateCategoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateCategoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.CategoryUpdateResp)
}

func (p *UpdateCategoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateCategoryResult) GetResult() interface{} {
	return p.Success
}

func selectBrandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.BrandSelectReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).SelectBrand(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SelectBrandArgs:
		success, err := handler.(product.ProductCatalogService).SelectBrand(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SelectBrandResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSelectBrandArgs() interface{} {
	return &SelectBrandArgs{}
}

func newSelectBrandResult() interface{} {
	return &SelectBrandResult{}
}

type SelectBrandArgs struct {
	Req *product.BrandSelectReq
}

func (p *SelectBrandArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.BrandSelectReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SelectBrandArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SelectBrandArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SelectBrandArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SelectBrandArgs) Unmarshal(in []byte) error {
	msg := new(product.BrandSelectReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SelectBrandArgs_Req_DEFAULT *product.BrandSelectReq

func (p *SelectBrandArgs) GetReq() *product.BrandSelectReq {
	if !p.IsSetReq() {
		return SelectBrandArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SelectBrandArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SelectBrandArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SelectBrandResult struct {
	Success *product.BrandSelectResp
}

var SelectBrandResult_Success_DEFAULT *product.BrandSelectResp

func (p *SelectBrandResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.BrandSelectResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SelectBrandResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SelectBrandResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SelectBrandResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SelectBrandResult) Unmarshal(in []byte) error {
	msg := new(product.BrandSelectResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SelectBrandResult) GetSuccess() *product.BrandSelectResp {
	if !p.IsSetSuccess() {
		return SelectBrandResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SelectBrandResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.BrandSelectResp)
}

func (p *SelectBrandResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SelectBrandResult) GetResult() interface{} {
	return p.Success
}

func insertBrandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.BrandInsertReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).InsertBrand(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *InsertBrandArgs:
		success, err := handler.(product.ProductCatalogService).InsertBrand(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*InsertBrandResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newInsertBrandArgs() interface{} {
	return &InsertBrandArgs{}
}

func newInsertBrandResult() interface{} {
	return &InsertBrandResult{}
}

type InsertBrandArgs struct {
	Req *product.BrandInsertReq
}

func (p *InsertBrandArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.BrandInsertReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *InsertBrandArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *InsertBrandArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *InsertBrandArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *InsertBrandArgs) Unmarshal(in []byte) error {
	msg := new(product.BrandInsertReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var InsertBrandArgs_Req_DEFAULT *product.BrandInsertReq

func (p *InsertBrandArgs) GetReq() *product.BrandInsertReq {
	if !p.IsSetReq() {
		return InsertBrandArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *InsertBrandArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InsertBrandArgs) GetFirstArgument() interface{} {
	return p.Req
}

type InsertBrandResult struct {
	Success *product.BrandInsertResp
}

var InsertBrandResult_Success_DEFAULT *product.BrandInsertResp

func (p *InsertBrandResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.BrandInsertResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *InsertBrandResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *InsertBrandResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *InsertBrandResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *InsertBrandResult) Unmarshal(in []byte) error {
	msg := new(product.BrandInsertResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *InsertBrandResult) GetSuccess() *product.BrandInsertResp {
	if !p.IsSetSuccess() {
		return InsertBrandResult_Success_DEFAULT
	}
	return p.Success
}

func (p *InsertBrandResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.BrandInsertResp)
}

func (p *InsertBrandResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InsertBrandResult) GetResult() interface{} {
	return p.Success
}

func deleteBrandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.BrandDeleteReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).DeleteBrand(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteBrandArgs:
		success, err := handler.(product.ProductCatalogService).DeleteBrand(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteBrandResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteBrandArgs() interface{} {
	return &DeleteBrandArgs{}
}

func newDeleteBrandResult() interface{} {
	return &DeleteBrandResult{}
}

type DeleteBrandArgs struct {
	Req *product.BrandDeleteReq
}

func (p *DeleteBrandArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.BrandDeleteReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteBrandArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteBrandArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteBrandArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteBrandArgs) Unmarshal(in []byte) error {
	msg := new(product.BrandDeleteReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteBrandArgs_Req_DEFAULT *product.BrandDeleteReq

func (p *DeleteBrandArgs) GetReq() *product.BrandDeleteReq {
	if !p.IsSetReq() {
		return DeleteBrandArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteBrandArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteBrandArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteBrandResult struct {
	Success *product.BrandDeleteResp
}

var DeleteBrandResult_Success_DEFAULT *product.BrandDeleteResp

func (p *DeleteBrandResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.BrandDeleteResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteBrandResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteBrandResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteBrandResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteBrandResult) Unmarshal(in []byte) error {
	msg := new(product.BrandDeleteResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteBrandResult) GetSuccess() *product.BrandDeleteResp {
	if !p.IsSetSuccess() {
		return DeleteBrandResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteBrandResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.BrandDeleteResp)
}

func (p *DeleteBrandResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteBrandResult) GetResult() interface{} {
	return p.Success
}

func updateBrandHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(product.BrandUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(product.ProductCatalogService).UpdateBrand(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateBrandArgs:
		success, err := handler.(product.ProductCatalogService).UpdateBrand(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateBrandResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateBrandArgs() interface{} {
	return &UpdateBrandArgs{}
}

func newUpdateBrandResult() interface{} {
	return &UpdateBrandResult{}
}

type UpdateBrandArgs struct {
	Req *product.BrandUpdateReq
}

func (p *UpdateBrandArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(product.BrandUpdateReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateBrandArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateBrandArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateBrandArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateBrandArgs) Unmarshal(in []byte) error {
	msg := new(product.BrandUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateBrandArgs_Req_DEFAULT *product.BrandUpdateReq

func (p *UpdateBrandArgs) GetReq() *product.BrandUpdateReq {
	if !p.IsSetReq() {
		return UpdateBrandArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateBrandArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateBrandArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateBrandResult struct {
	Success *product.BrandUpdateResp
}

var UpdateBrandResult_Success_DEFAULT *product.BrandUpdateResp

func (p *UpdateBrandResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(product.BrandUpdateResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateBrandResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateBrandResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateBrandResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateBrandResult) Unmarshal(in []byte) error {
	msg := new(product.BrandUpdateResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateBrandResult) GetSuccess() *product.BrandUpdateResp {
	if !p.IsSetSuccess() {
		return UpdateBrandResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateBrandResult) SetSuccess(x interface{}) {
	p.Success = x.(*product.BrandUpdateResp)
}

func (p *UpdateBrandResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateBrandResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListProducts(ctx context.Context, Req *product.ListProductsReq) (r *product.ListProductsResp, err error) {
	var _args ListProductsArgs
	_args.Req = Req
	var _result ListProductsResult
	if err = p.c.Call(ctx, "ListProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, Req *product.GetProductReq) (r *product.GetProductResp, err error) {
	var _args GetProductArgs
	_args.Req = Req
	var _result GetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchProducts(ctx context.Context, Req *product.SearchProductsReq) (r *product.SearchProductsResp, err error) {
	var _args SearchProductsArgs
	_args.Req = Req
	var _result SearchProductsResult
	if err = p.c.Call(ctx, "SearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InsertProduct(ctx context.Context, Req *product.InsertProductReq) (r *product.InsertProductResp, err error) {
	var _args InsertProductArgs
	_args.Req = Req
	var _result InsertProductResult
	if err = p.c.Call(ctx, "InsertProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SelectProduct(ctx context.Context, Req *product.SelectProductReq) (r *product.SelectProductResp, err error) {
	var _args SelectProductArgs
	_args.Req = Req
	var _result SelectProductResult
	if err = p.c.Call(ctx, "SelectProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteProduct(ctx context.Context, Req *product.DeleteProductReq) (r *product.DeleteProductResp, err error) {
	var _args DeleteProductArgs
	_args.Req = Req
	var _result DeleteProductResult
	if err = p.c.Call(ctx, "DeleteProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProduct(ctx context.Context, Req *product.UpdateProductReq) (r *product.UpdateProductResp, err error) {
	var _args UpdateProductArgs
	_args.Req = Req
	var _result UpdateProductResult
	if err = p.c.Call(ctx, "UpdateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SelectCategory(ctx context.Context, Req *product.CategorySelectReq) (r *product.CategorySelectResp, err error) {
	var _args SelectCategoryArgs
	_args.Req = Req
	var _result SelectCategoryResult
	if err = p.c.Call(ctx, "SelectCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InsertCategory(ctx context.Context, Req *product.CategoryInsertReq) (r *product.CategoryInsertResp, err error) {
	var _args InsertCategoryArgs
	_args.Req = Req
	var _result InsertCategoryResult
	if err = p.c.Call(ctx, "InsertCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteCategory(ctx context.Context, Req *product.CategoryDeleteReq) (r *product.CategoryDeleteResp, err error) {
	var _args DeleteCategoryArgs
	_args.Req = Req
	var _result DeleteCategoryResult
	if err = p.c.Call(ctx, "DeleteCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateCategory(ctx context.Context, Req *product.CategoryUpdateReq) (r *product.CategoryUpdateResp, err error) {
	var _args UpdateCategoryArgs
	_args.Req = Req
	var _result UpdateCategoryResult
	if err = p.c.Call(ctx, "UpdateCategory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SelectBrand(ctx context.Context, Req *product.BrandSelectReq) (r *product.BrandSelectResp, err error) {
	var _args SelectBrandArgs
	_args.Req = Req
	var _result SelectBrandResult
	if err = p.c.Call(ctx, "SelectBrand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InsertBrand(ctx context.Context, Req *product.BrandInsertReq) (r *product.BrandInsertResp, err error) {
	var _args InsertBrandArgs
	_args.Req = Req
	var _result InsertBrandResult
	if err = p.c.Call(ctx, "InsertBrand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteBrand(ctx context.Context, Req *product.BrandDeleteReq) (r *product.BrandDeleteResp, err error) {
	var _args DeleteBrandArgs
	_args.Req = Req
	var _result DeleteBrandResult
	if err = p.c.Call(ctx, "DeleteBrand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateBrand(ctx context.Context, Req *product.BrandUpdateReq) (r *product.BrandUpdateResp, err error) {
	var _args UpdateBrandArgs
	_args.Req = Req
	var _result UpdateBrandResult
	if err = p.c.Call(ctx, "UpdateBrand", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
